### ISSUE TITLE
Some icons are missing

### ISSUE THREAD

**Issue by mrcasals** [binggg/react-native-material-design-components#5]
I cannot use `list`, `face`, `question-answer` or `folder-open` icons. I'm using latest version (`v0.14`). When I used https://github.com/oblador/react-native-vector-icons directly I had no problem, so I guess it's a thing with the font face.

Can you update it to use the original version?

Thank you!

**Comment by binggg** [comment]
Yes, I choose the iconfont [materialdesignicons](https://materialdesignicons.com) provided. Beacuse the iconfont contain more material design style icon (about 1341 icons), not just icons by Google(about 796 icons).

You can find icon name from https://materialdesignicons.com. I think you can find the icons you mentioned because the icon name is different from https://github.com/oblador/react-native-vector-icons.

My idea is that if users need more or different icon, they can change the Icon file to implement custom.
